version: "3.8"

services:
  n8n:
    build:
      context: .
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_LOG_LEVEL=debug
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - CUSTOM_DOMAIN=${CUSTOM_DOMAIN}
    restart: unless-stopped

volumes:
  n8n_data:
    external: true